apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-myiagnka
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-myiagnka:36d053c725847b1e87e79c4c4810b889079132b1@sha256:7276df169a38cdbfe5eb31d75a81336401fe14b5fe918178bf924455263237ff
          name: container-image
